version: '3.7'
services:
  my_service: &my_service
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app

volumes:
  dbdata: {}
