default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: school_api_development
  username: postgres
  password: postgres
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

test:
  <<: *default
  database: school_api_test

production:
  <<: *default
  database: school_api_production
  username: school_api
  password: <%= ENV['SCHOOL_API_DATABASE_PASSWORD'] %>
